require_relative 'create_store_product.rb'
require_relative 'old_state.rb'
require_relative 'old_school.rb'
require_relative 'old_user.rb'
require_relative 'old_classroom_detail.rb'
require_relative 'old_classroom.rb'
require_relative 'old_otu_code.rb'
require_relative 'old_point.rb'
require_relative 'old_reward_detail.rb'
require_relative 'old_reward.rb'
require_relative 'old_reward_local.rb'
require_relative 'old_local_reward_category.rb'
require_relative 'old_reward_global.rb'
require_relative 'old_redeemed.rb'
require_relative 'old_reward_image.rb'
require_relative 'old_teacher_award.rb'
require_relative 'old_file_download.rb'
require_relative 'old_user_avatar.rb'
require_relative 'old_avatar.rb'

require_relative 'old_filter.rb'
require_relative 'old_filter_classroom.rb'
require_relative 'old_filter_state.rb'
require_relative 'old_filter_usertype.rb'
require_relative 'old_filter_school.rb'


