# Postgresql config
#
production:
  adapter: postgresql
  database: learning_earning_production

development:
  adapter: postgresql
  database: learning_earning_development

test: &test
  adapter: postgresql
  database: learning_earning_test

cucumber:
  <<: *test
